[package]
name = "fusionner"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[dependencies]
git2 = "0.6"
env_logger = "0.4.0"
log = "0.3"
docopt = "0.7.0"
rustc-serialize = "0.3"
toml = "0.2"
