[package]
name = "fusionner"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[dependencies]
docopt = "0.7.0"
env_logger = "0.4.0"
git2 = { path = "git2-rs", version = "0.6" }
lazy_static = "0.2"
log = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
toml = "0.2"
