[package]
name = "fusionner"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[dependencies]
docopt = "0.7.0"
env_logger = "0.4.0"
git2 = "0.6"
log = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
toml = "0.2"
